// expenses-react/src/components/FormComponent.js
import React, {Component} from 'react';
import './FormComponent.css';
import axios from 'axios';

class FormComponent extends Component{
    constructor(props){
        super(props)
        this.state = {
            itemName:'',
            itemPrice: ''
        };
        this.addItem = this.addItem.bind(this);
        this.handleChangeName = this.handleChangeName.bind(this);
        this.handleChangePrice = this.handleChangePrice.bind(this);
    }

    handleChangeName(event) {
        this.setState({itemName: event.target.value});
    }

    handleChangePrice(event){
        this.setState({itemPrice: event.target.value});
    }

    async addItem(){
        const data = {
            item: this.state.itemName,
            price: this.state.itemPrice
        };

        const resp = await axios.post('http://localhost:5040/expenses/create',data);
        console.log(resp);
    }

    render(){
        return (
            <div className="form-cont">
                <h1> Add a Expense </h1>
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2000px-React-icon.svg.png" alt=""/>
                    <div className="form-page">
                        <input type="text" placeholder="Input your item here" value={this.state.itemName} onChange={this.handleChangeName}/>
                        <input type="number" placeholder="Input the price of item" value={this.state.itemPrice} onChange={this.handleChangePrice}/>
                        <input type="submit" onClick={this.addItem}/>
                    </div>
            </div>
        );
    }
}

export default FormComponent;

// expenses-angular/src/app/form/form.component.ts
import { Component, OnInit } from '@angular/core';
import {Expense} from '../expense';
import {ExpensesService} from "../expenses.service";

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent implements OnInit {

  itemName: string;
  itemPrice: number;
  private data: {};

  constructor(private expensesService: ExpensesService) { }

  ngOnInit() {
    this.itemName = '';
    this.itemPrice = 0;
  }

  async saveExpense(){
    console.log(`name: ${this.itemName} Price: ${this.itemPrice}`);
    this.data = {
      item: this.itemName,
      price: this.itemPrice
    };
    await this.expensesService.saveExpense(this.data)
      .subscribe(res => {
        let id = res['_id'];
        console.log(res)
      }, (err) => {
        console.log(err);
      });
  }

}

<div class="form-cont">
  <h1> Add a Expense </h1>
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/250px-Angular_full_color_logo.svg.png" alt="">
  <div class="form-page">
    <input [(ngModel)]="itemName" type="text" placeholder="Input your item here" />
    <input [(ngModel)]="itemPrice" type="number" placeholder="Input the price of item"/>
    <input type="submit" (click)="saveExpense()">
  </div>
</div>
