// expenses-react/src/App.js
import './App.css';
import List from "./components/List";
import Form from "./components/Form";

function App() {
  return (
    <div className="Container">
      <div className="Form-Container">
        <h2>Add a new expense</h2>
        <Form />
      </div>
      <div className="List-Container">
        <h2>Expenses</h2>
        <List />
      </div>
    </div>
  );
}

export default App;

// expenses-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'expenses-angular';
}

<div class="container container-one">
  <app-form class="component component-one"></app-form>
</div>
<div class="container container-two">
  <app-list class="component"></app-list>
</div>
