// expenses-vue/src/components/ContentCard.vue
<template>
    <div class="">
        <div v-show="!edit">
            <div class="card">
                <p class="info">{{name}} - ${{price}}</p>
                <p class="button red" @click="deleteItem">Delete</p>
                <p class="button green" @click="editToggle">Edit</p>
            </div>
        </div>
        <div v-show="edit">
            <div class="card">
                <p class="info">Name: <input type="text" v-model="newname"> </p>
                <p class="info">Price: <input type="text" v-model="newprice"> </p>
                <p class="button green" @click="editItem">OK</p>
            </div>

        </div>

    </div>
</template>

<script>
    /**
     * Componente que contiene la información de un gasto específico
     */
    export default{
        name:'ContentCard',
        /**
         * data()
         *      Aquí se colocan las propiedades generales del componente
         * @returns {{newname: string, newprice: string, edit: boolean}}
         */
        data(){
            return{
                newname: this.name,
                newprice: this.price,
                edit: false
            }
        },
        /**
         * Aquí se definen las propiedades que van a ser explicítas
         * en el HTML del componente
         */
        props: ['id','name','price'],
        methods:{
            /**
             * Método que hace la petición al ws para eliminar un recurso
             * @returns {Promise<void>}
             */
            async deleteItem(){
                await axios.delete(`http://localhost:5040/expenses/${this.id}/delete`);
            },
            /**
             * Método que funciona como un switch para cambiar el estado de la variable edit.
             * La variable edit es usada para mostrar o no el formulario de edicion
             */
            editToggle(){
                this.edit = !this.edit;
            },
            /**
             * Método que hace la petición al ws para cambiar los datos de un recurso específico
             * @returns {Promise<void>}
             */
            async editItem(){
                const data = {
                    item: this.newname,
                    price: this.newprice
                }
                await axios.put(`http://localhost:5040/expenses/${this.id}/update`,data);
                this.editToggle()
            }
        }
    }
</script>

<style scoped>
    .card{
        background: #fff;
        //display: block;
        font-size: 16px;
        margin-bottom: 5%;
        width: 100%;
        font-family: 'Pacifico', cursive;
        -webkit-box-shadow: 0px 5px 4px #c0c0c09d;
        -moz-box-shadow: 0px 5px 4px #c0c0c09d;
        box-shadow: 0px 5px 4px #c0c0c09d;
        border:none;
        outline: none;
        float:left;
    }
    .info{
        float: left;
        width: 60%;
    }
    .button{
        float:left;
        width: 10%;
        //margin-left: %;
        vertical-align: center;
        cursor: pointer;
    }
    .red{
        color: #e74c3c;
        margin-left: -5%;
        margin-right: 15%;
    }
    .green{
        color: #2ecc71;
    }

    input[type="text"], input[type="number"] {
        margin-top: 2%;
        font-family: 'Pacifico', cursive;
        font-size: 16px;
        border: 1px solid #2ecc71;
        outline: none;
    }
</style>

// expenses-react/src/components/ContentCard.js
import React, {Component} from 'react';
import './ContentCard.css';
import axios from 'axios';

/**
 * Componente que contiene la información de un gasto específico
 */
class ContentCard extends Component {
    /**
     * Constructor donde se definen las propiedades del componente.
     * Aquí se puede definir la lista de estados y enlazar los métodos al componente.
     * @param props propiedades explícitas del componente
     */
    constructor(props) {
        super(props);
        this.state = {
            newName: this.props.name,
            newPrice: this.props.price,
            edit: false
        };
        this.editItem = this.editItem.bind(this);
        this.deleteItem = this.deleteItem.bind(this);
        this.editToggle = this.editToggle.bind(this);
        this.handleChangeName = this.handleChangeName.bind(this);
        this.handleChangePrice = this.handleChangePrice.bind(this);
    }

    /**
     * Método que hace la petición al ws para eliminar un recurso
     * @returns {Promise<void>}
     */
    async deleteItem() {
        console.log(this.props.id)
        const resp = await axios.delete(`http://localhost:5040/expenses/${this.props.id}/delete`);
        console.log(resp);
    }

    /**
     * Método que funciona como un switch para cambiar el estado de la variable edit.
     * La variable edit es usada para mostrar o no el formulario de edicion
     */
    editToggle() {
        this.setState({edit: !this.state.edit});
    }

    /**
     * Método que hace la petición al ws para cambiar los datos de un recurso específico
     * @returns {Promise<void>}
     */
    async editItem() {
        this.editToggle()

        const data = {
            item: this.state.newName,
            price: this.state.newPrice
        };
        const resp = await axios.put(`http://localhost:5040/expenses/${this.props.id}/update`, data);
        console.log(resp);
    }
    /**
     * Método que actualiza el estado del estado newName cuando cambia un input
     * @param event evento ejecutado
     */
    handleChangeName(event) {
        this.setState({newName: event.target.value});
        console.log(this.state.newName)
    }
    /**
     * Método que actualiza el estado del estado newPrice cuando cambia un input
     * @param event evento ejecutado
     */
    handleChangePrice(event){
        this.setState({newPrice: event.target.value});
    }
    /**
     * Método que renderiza el componente, aquí va el template del mismo.
     * @returns {*} template del componente
     */
    render() {
        return(
            !this.state.edit? <div className="card">
                <p className="info">{this.state.newName} - ${this.state.newPrice}</p>
                <p className="button red" onClick={this.deleteItem}>Delete</p>
                <p className="button green" onClick={this.editToggle}>Edit</p>
            </div> : <div className="card">
                <p className="info">Name: <input type="text" value={this.state.newName} onChange={this.handleChangeName}/></p>
                <p className="info">Price: <input type="text" value={this.state.newPrice} onChange={this.handleChangePrice}/></p>
                <p className="button green" onClick={this.editItem}>OK</p>
            </div>
        )

    }
}


export default ContentCard;
