// expenses-vue/src/components/ListComponent.vue
<template>
    <div>
        <div class="container-list">
            <h1> My Expenses </h1>
            <div class="list">
                <div v-for="item in listExpenses">
                    <ContentCard :id="item._id" :name="item.item" :price="item.price"></ContentCard>
                </div>
            </div>

        </div>

    </div>
</template>

<script>
    import ContentCard from './ContentCard.vue';
    export default {
        name: 'ListComponent',
        components:{
            ContentCard
        },
        data(){
            return {
                listExpenses: null
            }
        },
        async mounted(){
            await setInterval(this.getExpenses,1000)
        },
        methods:{
            async getExpenses(){
                const expenses = await axios.get('http://localhost:5040/expenses/')
                this.listExpenses = expenses.data;
            }
        }
    }
</script>

<style scoped>
    h1{
        font-size: 48px;
        color: #34495e;
        margin-bottom: -10%;
    }
    .container-list{
        display: grid;
        height: -webkit-fill-available;
    }

    .list{
        margin-top: 30%;
    }

</style>

// expenses-react/src/components/ListComponent.js
import React, { useEffect, useState } from 'react';
import './ListComponent.css';
import axios from 'axios';
import ContentCard from './ContentCard';

const ListComponent = props => {
    const [list, setList] = useState([]);

    const createdTasks = item => {
        return <ContentCard
            key={item._id}
            id={item._id}
            name={item.item}
            price={item.price}
        />
    };

    const getExpenses = async () => {
        const expenses = await axios.get('http://localhost:5040/expenses/');
        setList(expenses.data);
    };

    useEffect(() => {
        const interval = setInterval(getExpenses, 1000);

        return () => clearInterval(interval);
    });

    const listItems = list.map(createdTasks);

    return (
        <div className="container-list">
            <h1> My Expenses </h1>
            <div className="list">
                {listItems}
            </div>
        </div>
    );
}

export default ListComponent;
